const AUDIT_TABLES = Object.freeze({
  USUARIOS: "usuarios",
  ESTUDIANTES: "estudiantes",
  MOTOCICLETAS: "motocicletas",
  MOVIMIENTOS: "movimientos",
});

const AUDIT_TYPES = Object.freeze({
  CREAR_USUARIO: "CREAR_USUARIO",
  CREAR_ESTUDIANTE: "CREAR_ESTUDIANTE",
  ACTUALIZAR_ESTUDIANTE: "ACTUALIZAR_ESTUDIANTE",
  CREAR_MOTOCICLETA: "CREAR_MOTOCICLETA",
  ACTUALIZAR_MOTOCICLETA: "ACTUALIZAR_MOTOCICLETA",
  REGISTRAR_ENTRADA: "REGISTRAR_ENTRADA",
  REGISTRAR_SALIDA: "REGISTRAR_SALIDA",
});

module.exports = {
  AUDIT_TABLES,
  AUDIT_TYPES,
};
